version: '2'

volumes:
  database:
  opencats:

services:
  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_DATABASE=cats_dev
      - MYSQL_USER=cats
      - MYSQL_PASSWORD=password
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - database:/var/lib/mysql

  opencats:
    image: dmitriiageev/opencats
    build:
      context: .
    volumes:
      - opencats:/opencats

  php:
    image: opencats/php
    build:
      context: php/
    depends_on:
      - mysql
      - opencats
    volumes:
      - opencats:/opencats

  nginx:
    image: nginx
    depends_on:
      - opencats
      - mysql
      - php
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - opencats:/opencats
